### ISSUE TITLE
group.albums is None exception

### ISSUE THREAD

**Issue by pe7ro** [pe7ro/simple_dr_meter#1]
```
01, Reading and Focus: DR9
Official DR = 9, Median DR = 9.0
Analyzed all tracks in 11.39 seconds
writing log to /dr.txt
Traceback (most recent call last):
  File "/simple_dr_meter/main.py", line 268, in <module>
    main()
  File "/simple_dr_meter/main.py", line 145, in main
    write_log(f.write, dr_log_items, dr_mean)
  File "/simple_dr_meter/main.py", line 54, in write_log
    group_name = get_group_title(group)
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/simple_dr_meter/main.py", line 35, in get_group_title
    return f'{", ".join(group.performers)} — {", ".join(group.albums)}'
                                              ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: sequence item 0: expected str instance, NoneType found
```

**Comment by pe7ro** [comment]
```
  File "/simple_dr_meter/main.py", line 35, in get_group_title
    return f'{", ".join(group.performers)} — {", ".join(group.albums)}'
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: sequence item 0: expected str instance, NoneType found
```
